"""Categories definition for CodeAtlas (76 total: 12 fundamental groups, 12 ecosystem groups, 52 ecosystem domains)."""

CATEGORIES = [
    # 1. Fundamental Groups (12)
    {
        "id": "f-logic",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Logika & Sintaks Dasar",
        "description": "Belajar memberi instruksi yang jelas, menyimpan informasi, dan mengolahnya.",
        "sort_order": 1,
    },
    {
        "id": "f-data-algorithms",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Struktur Data & Algoritma",
        "description": "Mengorganisir data dalam memori dan merancang langkah penyelesaian masalah yang efisien.",
        "sort_order": 2,
    },
    {
        "id": "f-code-quality",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Paradigma & Kualitas Kode",
        "description": "Prinsip menyusun program agar mudah dibaca, diuji, dan dikembangkan bersama tim.",
        "sort_order": 3,
    },
    {
        "id": "f-errors",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Menangani Kesalahan",
        "description": "Mengenali bug, menangani kegagalan aplikasi secara anggun, dan memastikan kualitas melalui pengujian.",
        "sort_order": 4,
    },
    {
        "id": "f-systems",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Sistem, Memori & I/O",
        "description": "Memahami bagaimana program berinteraksi dengan memori perangkat keras, file, dan sistem operasi.",
        "sort_order": 5,
    },
    {
        "id": "f-tooling",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Modularitas & Tooling",
        "description": "Mengelola modul, paket dependensi, proses kompilasi, runtime, dan version control Git.",
        "sort_order": 6,
    },
    {
        "id": "f-web",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Jaringan & Web",
        "description": "Dasar komunikasi jaringan, protokol HTTP, arsitektur API, dan format pertukaran data.",
        "sort_order": 7,
    },
    {
        "id": "f-data",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Data & Database",
        "description": "Menyimpan data persisten, query relasional dengan SQL, dan merancang skema data aplikasi.",
        "sort_order": 8,
    },
    {
        "id": "f-security-access",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Keamanan & Akses",
        "description": "Mengamankan sistem dengan otentikasi, otorisasi, enkripsi, dan pencegahan kerentanan umum.",
        "sort_order": 9,
    },
    {
        "id": "f-concurrency-group",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Konkurensi",
        "description": "Menjalankan operasi konkuren, pemrosesan paralel, dan asynchronous programming.",
        "sort_order": 10,
    },
    {
        "id": "f-process",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Proses & Kebiasaan Kerja",
        "description": "Siklus pengembangan software (SDLC), deployment, logging sistem, dan dokumentasi teknis.",
        "sort_order": 11,
    },
    {
        "id": "f-overview",
        "parent_id": None,
        "layer": "fundamentals",
        "kind": "group",
        "title": "Payung Besar",
        "description": "Fondasi teori ilmu komputer yang menaungi seluruh dunia rekayasa perangkat lunak.",
        "sort_order": 12,
    },

    # 2. Ecosystem Groups (12)
    {
        "id": "e-core-tools",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Bahasa & Alat Inti",
        "description": "Pondasi ekosistem: bahasa pemrograman, compiler, runtime engine, package manager, dan build tools.",
        "sort_order": 13,
    },
    {
        "id": "e-frameworks-libraries",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Framework & Library",
        "description": "Kerangka kerja terstruktur, pustaka siap pakai, dan ORM untuk mempercepat pembuatan aplikasi.",
        "sort_order": 14,
    },
    {
        "id": "e-platforms",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Pengembangan per Platform",
        "description": "Ranah pengembangan frontend, backend, mobile, desktop, game, IoT, dan grafis.",
        "sort_order": 15,
    },
    {
        "id": "e-data-communication",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Data & Komunikasi",
        "description": "Teknologi database modern, komunikasi antar-layanan API, message brokers, dan caching.",
        "sort_order": 16,
    },
    {
        "id": "e-computing",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Ilmu Komputer",
        "description": "Peta ranah algoritma terapan, ragam paradigma, pemrograman sistem level rendah, dan CS fundamentals.",
        "sort_order": 17,
    },
    {
        "id": "e-architecture-design",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Arsitektur & Desain",
        "description": "Pola arsitektur monolitik vs microservices, katalog design patterns, dan sistem terdistribusi.",
        "sort_order": 18,
    },
    {
        "id": "e-infrastructure",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Infrastruktur & Jaringan",
        "description": "Jaringan produksi, sistem operasi server, web server, cloud computing, IaC, dan orkestrasi kontainer.",
        "sort_order": 19,
    },
    {
        "id": "e-quality-security",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Kualitas & Keamanan",
        "description": "Ekosistem pengujian software, alat debugging, keamanan aplikasi, cybersecurity, dan aksesibilitas.",
        "sort_order": 20,
    },
    {
        "id": "e-operations",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "DevOps & Operasional",
        "description": "Otomatisasi CI/CD, observabilitas metrik & log, lingkungan produksi, dan developer tools.",
        "sort_order": 21,
    },
    {
        "id": "e-advanced-data",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Data Lanjutan & AI",
        "description": "Pipeline data engineering, data science & analitik statistik, hingga kecerdasan buatan & machine learning.",
        "sort_order": 22,
    },
    {
        "id": "e-collaboration",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Proses & Kolaborasi",
        "description": "Platform kolaborasi kode, proses rekayasa Agile, desain UI/UX, dokumentasi API, dan lokalisasi.",
        "sort_order": 23,
    },
    {
        "id": "e-advanced-optional",
        "parent_id": None,
        "layer": "ecosystem",
        "kind": "group",
        "title": "Opsional/Lanjutan",
        "description": "Teknologi khusus seperti desentralisasi Web3/Blockchain dan etika lisensi open source.",
        "sort_order": 24,
    },

    # 3. Ecosystem Domains (52)
    # Under e-core-tools (5)
    {
        "id": "e-languages",
        "parent_id": "e-core-tools",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Bahasa Pemrograman",
        "description": "Peta ragam bahasa pemrograman: tipikal kegunaan, kelebihan, dan ekosistem pendukungnya.",
        "sort_order": 25,
    },
    {
        "id": "e-compilers",
        "parent_id": "e-core-tools",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Compiler/Interpreter",
        "description": "Penerjemah kode sumber ke instruksi mesin: AOT, JIT, bytecode, dan transpiler.",
        "sort_order": 26,
    },
    {
        "id": "e-runtime",
        "parent_id": "e-core-tools",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Runtime",
        "description": "Lingkungan eksekusi yang menyediakan garbage collection, event loop, dan API sistem.",
        "sort_order": 27,
    },
    {
        "id": "e-package-managers",
        "parent_id": "e-core-tools",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Package Manager",
        "description": "Alat pengelola pustaka eksternal, resolusi versi, dan dependensi proyek (npm, pub, pip, cargo).",
        "sort_order": 28,
    },
    {
        "id": "e-build-tools",
        "parent_id": "e-core-tools",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Build Tools",
        "description": "Otomatisasi bundling, minifikasi kode, kompilasi aset, dan pembuatan artefak siap rilis.",
        "sort_order": 29,
    },

    # Under e-frameworks-libraries (3)
    {
        "id": "e-frameworks",
        "parent_id": "e-frameworks-libraries",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Framework",
        "description": "Kerangka kerja penentu struktur aplikasi dengan aturan inversi kendali (IoC).",
        "sort_order": 30,
    },
    {
        "id": "e-libraries",
        "parent_id": "e-frameworks-libraries",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Library",
        "description": "Koleksi fungsi dan modul spesifik yang dipanggil oleh aplikasi sesuai kebutuhan.",
        "sort_order": 31,
    },
    {
        "id": "e-orm",
        "parent_id": "e-frameworks-libraries",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "ORM/Query Builder",
        "description": "Penjembatan antara model data berorientasi objek dalam kode dengan tabel database SQL.",
        "sort_order": 32,
    },

    # Under e-platforms (7)
    {
        "id": "e-frontend",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Frontend",
        "description": "Pengembangan antarmuka pengguna berbasis browser menggunakan HTML, CSS, dan JavaScript/TypeScript.",
        "sort_order": 33,
    },
    {
        "id": "e-backend",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Backend",
        "description": "Pengembangan logika bisnis sisi server, pemrosesan data, autentikasi, dan penyedia API.",
        "sort_order": 34,
    },
    {
        "id": "e-mobile",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Mobile",
        "description": "Pengembangan aplikasi untuk sistem operasi ponsel pintar (Android & iOS) secara native atau cross-platform.",
        "sort_order": 35,
    },
    {
        "id": "e-desktop",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Desktop",
        "description": "Pembuatan aplikasi komputer untuk sistem operasi Windows, macOS, dan Linux.",
        "sort_order": 36,
    },
    {
        "id": "e-games",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Game Development",
        "description": "Pengembangan permainan interaktif dengan game engine, physics simulator, dan rendering pipa grafis.",
        "sort_order": 37,
    },
    {
        "id": "e-embedded",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Embedded Systems/IoT",
        "description": "Pemrograman mikrokontroler dan perangkat keras pintar dengan sumber daya memori sangat terbatas.",
        "sort_order": 38,
    },
    {
        "id": "e-graphics",
        "parent_id": "e-platforms",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Graphics Programming",
        "description": "Pemrograman visual komputer, manipulasi shader GPU, dan rendering 2D/3D interaktif.",
        "sort_order": 39,
    },

    # Under e-data-communication (4)
    {
        "id": "e-databases",
        "parent_id": "e-data-communication",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Database",
        "description": "Ragam sistem penyimpanan data: SQL relasional, NoSQL dokumen, key-value, dan grafis.",
        "sort_order": 40,
    },
    {
        "id": "e-api-communication",
        "parent_id": "e-data-communication",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "API & Communication",
        "description": "Standar dan arsitektur komunikasi layanan modern: REST, GraphQL, gRPC, dan WebSocket.",
        "sort_order": 41,
    },
    {
        "id": "e-message-brokers",
        "parent_id": "e-data-communication",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Message Queue/Broker",
        "description": "Sistem antrean pesan asinkron untuk decoupling layanan berskala besar (RabbitMQ, Kafka, SQS).",
        "sort_order": 42,
    },
    {
        "id": "e-caching",
        "parent_id": "e-data-communication",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Caching",
        "description": "Penyimpanan data berkecepatan tinggi dalam RAM untuk mengurangi beban database dan mempercepat respons.",
        "sort_order": 43,
    },

    # Under e-computing (4)
    {
        "id": "e-dsa",
        "parent_id": "e-computing",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Data Structures & Algorithms",
        "description": "Peta struktur data tingkat lanjut (Tree, Graph, Trie) dan algoritma optimasi pencarian.",
        "sort_order": 44,
    },
    {
        "id": "e-paradigms",
        "parent_id": "e-computing",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Paradigma Pemrograman",
        "description": "Karakteristik pemrograman imperatif, deklaratif, berorientasi objek, fungsional, dan reaktif.",
        "sort_order": 45,
    },
    {
        "id": "e-system-programming",
        "parent_id": "e-computing",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "System Programming",
        "description": "Pemrograman tingkat rendah berkecepatan tinggi dengan kendali langsung terhadap memori dan hardware.",
        "sort_order": 46,
    },
    {
        "id": "e-computer-science",
        "parent_id": "e-computing",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Computer Science Fundamentals",
        "description": "Landasan teori: teori komputasi, struktur logika biner, automata, dan arsitektur komputer.",
        "sort_order": 47,
    },

    # Under e-architecture-design (3)
    {
        "id": "e-architecture",
        "parent_id": "e-architecture-design",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Software Architecture",
        "description": "Pola organisasi sistem tingkat makro: arsitektur berlapis, clean architecture, dan microservices.",
        "sort_order": 48,
    },
    {
        "id": "e-patterns",
        "parent_id": "e-architecture-design",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Design Pattern",
        "description": "Pola solusi berulang untuk persoalan desain objek (Creational, Structural, Behavioral).",
        "sort_order": 49,
    },
    {
        "id": "e-distributed",
        "parent_id": "e-architecture-design",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Distributed Systems",
        "description": "Sistem yang beroperasi di banyak server terpisah: teorema CAP, konsensus, dan replikasi data.",
        "sort_order": 50,
    },

    # Under e-infrastructure (7)
    {
        "id": "e-networking",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Networking",
        "description": "Lapisan protokol komunikasi fisik dan logis (TCP/IP, DNS, routing, firewall, dan TLS/SSL).",
        "sort_order": 51,
    },
    {
        "id": "e-operating-systems",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Operating System",
        "description": "Manajemen proses, thread, sistem file, dan izin keamanan pada server Linux/Unix.",
        "sort_order": 52,
    },
    {
        "id": "e-shells",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Terminal/Shell",
        "description": "Navigasi antarmuka baris perintah, scripting Bash/Zsh/PowerShell, dan otomatisasi tugas server.",
        "sort_order": 53,
    },
    {
        "id": "e-web-servers",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Web Server/Reverse Proxy",
        "description": "Peladen web dan proksi pembalik untuk load balancing, SSL termination, dan routing trafik (Nginx, Caddy).",
        "sort_order": 54,
    },
    {
        "id": "e-cloud",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Cloud Computing",
        "description": "Layanan komputasi awan on-demand (AWS, GCP, Azure) dalam model IaaS, PaaS, dan Serverless.",
        "sort_order": 55,
    },
    {
        "id": "e-iac",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Infrastructure as Code",
        "description": "Mendefinisikan dan mengelola infrastruktur server melalui berkas kode deklaratif (Terraform, Ansible).",
        "sort_order": 56,
    },
    {
        "id": "e-orchestration",
        "parent_id": "e-infrastructure",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Container Orchestration",
        "description": "Manajemen siklus hidup kontainer dalam skala klaster server otomatis (Kubernetes, Docker Swarm).",
        "sort_order": 57,
    },

    # Under e-quality-security (5)
    {
        "id": "e-testing",
        "parent_id": "e-quality-security",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Testing",
        "description": "Piramida pengujian perangkat lunak: Unit testing, Integration testing, dan End-to-End (E2E) testing.",
        "sort_order": 58,
    },
    {
        "id": "e-debugging",
        "parent_id": "e-quality-security",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Debugging",
        "description": "Metode dan alat investigasi kerusakan program menggunakan debugger breakpoint, stack trace, dan memory profiler.",
        "sort_order": 59,
    },
    {
        "id": "e-security",
        "parent_id": "e-quality-security",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Security",
        "description": "Penerapan prinsip pertahanan keamanan aplikasi web dan mobile (OWASP Top 10, sanitasi input).",
        "sort_order": 60,
    },
    {
        "id": "e-cybersecurity",
        "parent_id": "e-quality-security",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Cybersecurity",
        "description": "Perlindungan aset digital, enkripsi data, deteksi intrusi jaringan, dan analisis ancaman siber.",
        "sort_order": 61,
    },
    {
        "id": "e-accessibility",
        "parent_id": "e-quality-security",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Accessibility",
        "description": "Memastikan aplikasi dapat digunakan dengan nyaman oleh semua pengguna termasuk penyandang disabilitas (a11y/WCAG).",
        "sort_order": 62,
    },

    # Under e-operations (4)
    {
        "id": "e-devops",
        "parent_id": "e-operations",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "DevOps",
        "description": "Kultur dan praktik penggabungan pengembangan software dengan operasional melalui otomatisasi CI/CD.",
        "sort_order": 63,
    },
    {
        "id": "e-observability",
        "parent_id": "e-operations",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Observability",
        "description": "Pemantauan kesehatan sistem melalui tiga pilar: logging terpusat, metrik performa, dan distributed tracing.",
        "sort_order": 64,
    },
    {
        "id": "e-production",
        "parent_id": "e-operations",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Deployment & Production",
        "description": "Strategi merilis kode ke lingkungan produksi tanpa downtime (Blue-Green, Canary, Rolling updates).",
        "sort_order": 65,
    },
    {
        "id": "e-developer-tools",
        "parent_id": "e-operations",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Developer Tools",
        "description": "Ekosistem alat bantu produktivitas engineer: IDE, ekstensi linter, formatters, dan CLI utilities.",
        "sort_order": 66,
    },

    # Under e-advanced-data (3)
    {
        "id": "e-data-engineering",
        "parent_id": "e-advanced-data",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Data Engineering",
        "description": "Pembangunan pipa aliran data berskala besar, data warehouse, data lake, dan proses ETL/ELT.",
        "sort_order": 67,
    },
    {
        "id": "e-data-science",
        "parent_id": "e-advanced-data",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Data Science & Analytics",
        "description": "Eksplorasi data, pemodelan statistik, dan visualisasi untuk menemukan wawasan bisnis yang actionable.",
        "sort_order": 68,
    },
    {
        "id": "e-ai-ml",
        "parent_id": "e-advanced-data",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "AI/Machine Learning",
        "description": "Model pembelajaran mesin, deep learning, Large Language Models (LLM), dan integrasi inferensi AI.",
        "sort_order": 69,
    },

    # Under e-collaboration (5)
    {
        "id": "e-version-control",
        "parent_id": "e-collaboration",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Version Control",
        "description": "Strategi kolaborasi riwayat kode: branching model (GitFlow/Trunk-based), pull requests, dan code review.",
        "sort_order": 70,
    },
    {
        "id": "e-engineering-process",
        "parent_id": "e-collaboration",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Software Engineering Process",
        "description": "Metodologi manajemen proyek rekayasa software: Agile Scrum, Kanban, Sprint, dan mitigasi risiko.",
        "sort_order": 71,
    },
    {
        "id": "e-ui-ux",
        "parent_id": "e-collaboration",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "UI/UX untuk Development",
        "description": "Prinsip desain antarmuka dan pengalaman pengguna: design system, wireframe handoff, dan heuristik kegunaan.",
        "sort_order": 72,
    },
    {
        "id": "e-technical-docs",
        "parent_id": "e-collaboration",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Technical Documentation & API Design",
        "description": "Standar dokumentasi teknis, spesifikasi API deklaratif (OpenAPI/Swagger), dan panduan arsitektur ADR.",
        "sort_order": 73,
    },
    {
        "id": "e-localization",
        "parent_id": "e-collaboration",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Localization & Internationalization",
        "description": "Teknik adaptasi aplikasi ke beragam bahasa, zona waktu, format mata uang, dan budaya (i18n & l10n).",
        "sort_order": 74,
    },

    # Under e-advanced-optional (2)
    {
        "id": "e-blockchain",
        "parent_id": "e-advanced-optional",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Blockchain/Web3",
        "description": "Buku besar terdistribusi, konsensus kriptografis, smart contracts, dan aplikasi terdesentralisasi (DApp).",
        "sort_order": 75,
    },
    {
        "id": "e-open-source",
        "parent_id": "e-advanced-optional",
        "layer": "ecosystem",
        "kind": "domain",
        "title": "Software Licensing & Open Source",
        "description": "Etika dan kepatuhan hukum lisensi perangkat lunak: MIT, Apache 2.0, GPL, dan pengenal SPDX.",
        "sort_order": 76,
    },
]
